### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by xbxymax** [instance01/MinigamesAPI#23]

**Comment by xbxymax** [comment]
MGDeathRun
Regardless of how I set it, he kept the data in stat.yml
I tested other small games and all of them had the same problem 

[code]
mysql:
  enabled: true
  host: 127.0.0.1
  user: root
  pw: xxx
  database: mcminigames
[/code]
[code]
[17:57:00 WARN]: [MinigamesLib] exception
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''player', 'points', 'wins', 'loses', 'kills', 'deaths', 'uuid', 'gamepoints') VA' at line 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595) ~[j15spleef.jar:git-Paper-1104]
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468) ~[j15spleef.jar:git-Paper-1104]
        at com.comze_instancelabs.minigamesapi.sql.MainSQL.updateLosterStats(MainSQL.java:306) ~[?:?]
        at com.comze_instancelabs.minigamesapi.sql.MainSQL.updateLoserStats(MainSQL.java:270) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Stats.lose(Stats.java:95) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Rewards.giveWinReward(Rewards.java:384) ~[?:?]
        at com.comze_instancelabs.minigamesapi.Arena.lambda$leavePlayerRaw$13(Arena.java:1347) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) [j15spleef.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [j15spleef.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [j15spleef.jar:git-Paper-1104]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[/code]

**Comment by Dylan-Mann** [comment]
Any news on this? Im having the same issue
